export default {
  UPDATE_CATEGORY: { type: 'UPDATE_CATEGORY' },
  REMOVE_CATEGORY: { type: 'REMOVE_CATEGORY' },
  CATEGORY_REQUESTED: { type: 'CATEGORY_REQUESTED' },
  CATEGORY_SUCCEEDED: { type: 'CATEGORY_SUCCEEDED' },
  CATEGORY_FAILED: { type: 'CATEGORY_FAILED' },
}