export default {
  GET_CATEGORY: { type: 'GET_CATEGORY'},
  CATEGORY_REQUESTED: { type: 'CATEGORY_REQUESTED'},
  CATEGORY_SUCCEEDED: { type: 'CATEGORY_SUCCEEDED'},
  CATEGORY_FAILED: { type: 'CATEGORY_FAILED'},
}